### ISSUE TITLE
apipost转openapi3.0

### ISSUE THREAD

**Issue by nigiwen** [chenshuai2144/openapi2typescript#166]
```
➜ pnpm run openapi

> @ openapi E:\demo-openapi
> esno openapi.config.ts

[GenSDK] gen service param error: TypeError: Cannot read properties of undefined (reading 'schema')
    at ServiceGenerator.getBodyTP (E:\demo-openapi\node_modules\.pnpm\@umijs+openapi@1.12.1_chokidar@3.6.0\node_modules\@umijs\openapi\dist\serviceGenerator.js:468:46)
    at E:\demo-openapi\node_modules\.pnpm\@umijs+openapi@1.12.1_chokidar@3.6.0\node_modules\@umijs\openapi\dist\serviceGenerator.js:345:39
    at Array.map (<anonymous>)
    at E:\demo-openapi\node_modules\.pnpm\@umijs+openapi@1.12.1_chokidar@3.6.0\node_modules\@umijs\openapi\dist\serviceGenerator.js:340:18
    at Array.map (<anonymous>)
    at ServiceGenerator.getServiceTP (E:\demo-openapi\node_modules\.pnpm\@umijs+openapi@1.12.1_chokidar@3.6.0\node_modules\@umijs\openapi\dist\serviceGenerator.js:332:14)
    at ServiceGenerator.genFile (E:\demo-openapi\node_modules\.pnpm\@umijs+openapi@1.12.1_chokidar@3.6.0\node_modules\@umijs\openapi\dist\serviceGenerator.js:298:14)
    at E:\demo-openapi\node_modules\.pnpm\@umijs+openapi@1.12.1_chokidar@3.6.0\node_modules\@umijs\openapi\dist\index.js:76:22
    at Generator.next (<anonymous>)
    at fulfilled (E:\demo-openapi\node_modules\.pnpm\tslib@2.6.3\node_modules\tslib\tslib.js:166:62)
E:\demo-openapi\node_modules\.pnpm\@umijs+openapi@1.12.1_chokidar@3.6.0\node_modules\@umijs\openapi\dist\serviceGenerator.js:468
        const schema = reqContent[mediaType].schema || DEFAULT_SCHEMA;
                                             ^

TypeError: Cannot read properties of undefined (reading 'schema')
    at ServiceGenerator.getBodyTP (E:\demo-openapi\node_modules\.pnpm\@umijs+openapi@1.12.1_chokidar@3.6.0\node_modules\@umijs\openapi\dist\serviceGenerator.js:468:46)
    at E:\demo-openapi\node_modules\.pnpm\@umijs+openapi@1.12.1_chokidar@3.6.0\node_modules\@umijs\openapi\dist\serviceGenerator.js:345:39        
    at Array.map (<anonymous>)
    at E:\demo-openapi\node_modules\.pnpm\@umijs+openapi@1.12.1_chokidar@3.6.0\node_modules\@umijs\openapi\dist\serviceGenerator.js:340:18        
    at Array.map (<anonymous>)
    at ServiceGenerator.getServiceTP (E:\demo-openapi\node_modules\.pnpm\@umijs+openapi@1.12.1_chokidar@3.6.0\node_modules\@umijs\openapi\dist\serviceGenerator.js:332:14)
    at ServiceGenerator.genFile (E:\demo-openapi\node_modules\.pnpm\@umijs+openapi@1.12.1_chokidar@3.6.0\node_modules\@umijs\openapi\dist\serviceGenerator.js:298:14)
    at E:\demo-openapi\node_modules\.pnpm\@umijs+openapi@1.12.1_chokidar@3.6.0\node_modules\@umijs\openapi\dist\index.js:76:22
    at Generator.next (<anonymous>)
    at fulfilled (E:\demo-openapi\node_modules\.pnpm\tslib@2.6.3\node_modules\tslib\tslib.js:166:62)

Node.js v20.14.0
```

**Comment by rookie-luochao** [comment]
你可以看看 openapi-ts-request, 我基于陈帅大佬的库，暴力改造了一下，我会持续维护下去，应该解决了你这个bug
